name: base
channels:
  - r
  - gurobi
  - http://conda.anaconda.org/gurobi
  - conda-forge
  - defaults
dependencies:
  - gurobi=9.1.1=py37_0
  - pandas=0.24.2=py37h0a44026_0
  - numpy==1.16.4
  - matplotlib=3.0.3=py37h54f8f79_0
  - matplotlib-base=3.1.1=py37h3a684a6_1