# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
# conda config --add channels http://conda.anaconda.org/gurobi

name: condaenv2
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- gurobi
- pandas
- numpy
- matplotlib
- pip